packages:
  - "apps/store"
  - "apps/admin"
  - "apps/api"
  - "apps/workers"
  - "packages/database"
  - "packages/types"
  - "packages/validators"
  - "packages/trpc"
  - "packages/ui"
allowBuilds:
  argon2: true
  esbuild: true
  sharp: true
  unrs-resolver: true
