"use client";

import Link from "next/link";
import { ArrowLeft, ShoppingBag, Trash2 } from "lucide-react";
import { formatPrice } from "@/lib/utils";
import { useHydrated } from "@/hooks/use-hydrated";
import { useCart, useCartCount, useCartTotal } from "@/store/cart";
import { CartItem } from "@/components/cart/item";
import { EmptyState } from "@/components/ui/empty-state";

export default function CartPage() {
  const hydrated = useHydrated(); const items = useCart((state) => state.items); const clear = useCart((state) => state.clear); const count = useCartCount(); const total = useCartTotal();
  if (!hydrated) return <div className="mx-auto max-w-[1100px] px-4 py-12 sm:px-6" />;
  if (items.length === 0) return <div className="mx-auto max-w-[1100px] px-4 py-24 sm:px-6"><EmptyState title="Tu carrito está vacío" description="Explorá el catálogo y agregá productos para comenzar tu compra." actionLabel="Explorar catálogo" actionHref="/" /></div>;
  return <div className="mx-auto max-w-[1100px] px-4 py-8 sm:px-6"><div className="flex items-center justify-between gap-4"><h1 className="text-[22px] font-bold text-cc-text">Tu carrito <span className="text-[15px] font-medium text-cc-muted">({count} {count === 1 ? "producto" : "productos"})</span></h1><Link href="/" className="cc-focus-ring flex min-h-11 items-center gap-1.5 text-[13px] font-medium text-cc-primary hover:underline"><ArrowLeft className="h-4 w-4" strokeWidth={1.75} />Seguir comprando</Link></div><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_340px]"><section className="rounded-cc-lg border border-cc-border bg-cc-shell px-5">{items.map((item) => <CartItem key={item.product.id} item={item} />)}<div className="flex justify-end py-4"><button type="button" onClick={clear} className="cc-focus-ring flex min-h-11 items-center gap-1.5 text-[13px] font-medium text-cc-muted transition-[color] duration-[var(--cc-duration-fast)] ease-cc-out hover:text-cc-danger"><Trash2 className="h-4 w-4" strokeWidth={1.75} />Vaciar carrito</button></div></section><aside className="h-fit rounded-cc-lg border border-cc-border bg-cc-shell p-5 shadow-cc-sm lg:sticky lg:top-[84px]"><h2 className="text-[15px] font-bold text-cc-text">Resumen</h2><div className="mt-4 space-y-2.5 text-[13px]"><div className="flex items-center justify-between"><span className="text-cc-secondary">Subtotal</span><span className="font-semibold tabular-nums text-cc-text">{formatPrice(total)}</span></div><div className="flex items-center justify-between"><span className="text-cc-secondary">Envío</span><span className="font-semibold text-cc-success">Gratis</span></div><hr className="border-cc-border-subtle" /><div className="flex items-center justify-between text-[15px]"><span className="font-bold text-cc-text">Total</span><span className="font-extrabold tabular-nums tracking-tight text-cc-text">{formatPrice(total)}</span></div></div><Link href="/checkout" className="cc-focus-ring mt-5 flex h-12 w-full items-center justify-center gap-2 rounded-cc-sm bg-cc-primary text-[14px] font-bold text-cc-shell shadow-cc-sm transition-[background-color,transform] duration-[var(--cc-duration-fast)] ease-cc-out hover:-translate-y-px hover:bg-cc-primary-hover active:scale-[0.98]"><ShoppingBag className="h-[18px] w-[18px]" strokeWidth={1.75} />Ir al pago</Link><p className="mt-3 text-center text-[11px] text-cc-muted">Impuestos calculados en el pago</p></aside></div></div>;
}
