"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { motion } from "motion/react";
import { AlertCircle, Loader2, Lock, Mail } from "lucide-react";
import { useAuth } from "@/store/auth";
import { toast } from "@/store/toast";

export function LoginForm() {
  const router = useRouter(); const returnTo = useSearchParams().get("returnTo") || "/account"; const login = useAuth((state) => state.login);
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!/^\S+@\S+\.\S+$/.test(email)) { setError("Ingresá un correo válido"); return; } if (!password) { setError("Ingresá tu contraseña"); return; } setError(""); setLoading(true); const ok = await login(email, password); if (ok) { toast.success("Sesión iniciada", { description: email }); router.replace(returnTo); return; } setLoading(false); }
  const inputClass = "cc-focus-ring h-12 w-full rounded-cc-sm border border-cc-border bg-cc-shell pl-9 pr-3 text-[14px] text-cc-text outline-none transition-[border-color,box-shadow] duration-[var(--cc-duration-fast)] ease-cc-out placeholder:text-cc-faint focus:border-cc-primary";
  return <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.15, ease: [0.22, 1, 0.36, 1] }}><h1 className="text-[28px] font-extrabold tracking-tight text-cc-text">Iniciá sesión</h1><p className="mt-2 text-[14px] leading-6 text-cc-muted">Accedé a tus pedidos, puntos y beneficios.</p><form onSubmit={submit} className="mt-8 space-y-5">{error && <motion.p role="alert" initial={{ opacity: 0, transform: "translateY(-4px)" }} animate={{ opacity: 1, transform: "translateY(0px)" }} transition={{ duration: 0.15, ease: [0.22, 1, 0.36, 1] }} className="flex items-center gap-2 rounded-cc-sm bg-cc-danger-soft px-3 py-2.5 text-[13px] font-medium text-cc-danger"><AlertCircle className="h-4 w-4" strokeWidth={1.75} />{error}</motion.p>}<label className="flex flex-col gap-1.5"><span className="text-[12px] font-semibold text-cc-secondary">Correo</span><span className="relative"><Mail className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-cc-muted" strokeWidth={1.75} /><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="tucorreo@ejemplo.com" autoComplete="email" className={inputClass} /></span></label><label className="flex flex-col gap-1.5"><span className="flex items-center justify-between text-[12px] font-semibold text-cc-secondary">Contraseña<a href="mailto:soporte@cloudcommerce.com?subject=Recuperar%20contraseña" className="cc-focus-ring font-medium text-cc-primary hover:underline">¿Olvidaste tu contraseña?</a></span><span className="relative"><Lock className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-cc-muted" strokeWidth={1.75} /><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="••••••••" autoComplete="current-password" className={inputClass} /></span></label><button type="submit" disabled={loading} className="cc-focus-ring flex h-12 w-full items-center justify-center gap-2 rounded-full bg-cc-primary text-[14px] font-bold text-cc-shell transition-[background-color,transform] duration-[var(--cc-duration-fast)] ease-cc-out hover:bg-cc-primary-hover active:scale-[0.98] disabled:opacity-70">{loading && <Loader2 className="h-4 w-4 animate-spin" />}Iniciar sesión</button></form><p className="mt-7 text-center text-[13px] text-cc-muted">¿No tenés cuenta? <Link href={`/register?returnTo=${encodeURIComponent(returnTo)}`} className="cc-focus-ring font-semibold text-cc-primary hover:underline">Registrate</Link></p></motion.div>;
}
